### ISSUE TITLE
Compile Error on installation

### ISSUE THREAD

**Issue by AElimrani** [PlotPyStack/PlotPy#2]
Hi! While installing plotpy from the repo using pip on Windows 11 with VS2022 and python 3.12 installed, I encountered this error in the compile step:
<img width="970" alt="image" src="https://github.com/PlotPyStack/PlotPy/assets/30512804/a5e3405e-4801-456c-8c21-186fc11563ef">

If I try to install it without pointing to the repo, I get even more compile errors, so at least it seems like the latest commit has less issues. 

Thank you!
(I really like your tools by the way, super cool stuff!)

**Comment by AElimrani** [comment]
Works now! Thank you!!

**Comment by PierreRaybaut** [comment]
You're welcome. 
Thanks for the feedback.
